#65 - Cache managed identity access token
TraGicCode/tragiccode-azure_key_vault pull request #66
Opened 2021-04-18 17:10 UTC by dowlingw

Modifies `lookup.rb` to cache managed identity access token

2021-04-19 20:57 UTC, TraGicCode commented
Hey @dowlingw,

Thank you for the Pull Request.  Do you happen to know if a newer version of puppet changed/removed the methods i was originally using which caused the caching to be broken for you?

Thanks!

2021-04-21 12:14 UTC, dowlingw commented
`Puppet::LookupContext` is still supported, but having a look through history it looks like the `context.cache()` was never implemented for the access token in `lookup.rb`, so from what I can see this has likely never been caching the access token.

2021-04-22 01:48 UTC, TraGicCode approved these changes

2021-04-22 01:48 UTC, TraGicCode commented on lib/puppet/functions/azure_key_vault/lookup.rb
> +      context.cache('access_token', access_token)
wow, i cannot believe i actually never cached the value!

2021-04-22 01:51 UTC, TraGicCode requested changes

2021-04-22 01:51 UTC, TraGicCode commented on lib/puppet/functions/azure_key_vault/lookup.rb
> +    if access_token.nil?
wow, i cannot believe i actually never cached the value!!!

Can you write a unit test (https://github.com/TraGicCode/tragiccode-azure_key_vault/blob/master/spec/functions/azure_key_vault_lookup_spec.rb) to assert that the value is stored in the cache when it's not returned from the cache?

2021-04-22 02:14 UTC, TraGicCode commented
Hey @dowlingw ,

Ignore all comments above this one.  Thanks for fixing this bug! Can you complete the following?

1. Add a unit test to verify that the access token is cached when it's fetched because it was not found in the cache? ( Add this here https://github.com/TraGicCode/tragiccode-azure_key_vault/blob/master/spec/functions/azure_key_vault_lookup_spec.rb )

2021-04-22 02:15 UTC, TraGicCode requested changes
Hey @dowlingw ,

Ignore all comments above this one.  Thanks for fixing this bug! Can you complete the following?

1. Add a unit test to verify that the access token is cached when it's fetched because it was not found in the cache? ( Add this here https://github.com/TraGicCode/tragiccode-azure_key_vault/blob/master/spec/functions/azure_key_vault_lookup_spec.rb )

2021-04-22 21:22 UTC, TraGicCode approved these changes
LGTM.  Thank you for your contribution!

2021-04-22 21:23 UTC, merged