Added the ability to specify a user-assigned managed identity for access to the Azure Key Vault
TraGicCode/tragiccode-azure_key_vault pull request #79
Opened 2021-07-28 18:30 UTC by victorsecarin

By default, a system-assigned managed identity is expected to be in place and provide access to the Key Vault. Thus the module expects to have nothing to do in order to gain access; it will just pull secrets and expect that to work.
We can instead specify a user-assigned managed identity to use, identified by either its 'client_id' or its 'object_id'. Both these strings are formatted like uids and  should be available from Azure upon creating the managed identity.

2021-07-29 04:04 UTC, TraGicCode commented
Hey @victorsecarin ,

Thanks for submitting this PR.  

It appears this feature went to public preview this month ( https://azure.microsoft.com/en-us/updates/azure-automation-user-assigned-identities/ | https://azure.microsoft.com/en-us/updates/?status=inpreview ) which means it's hot off the press.  Being public preview this seems like it represents some risk in which microsoft might decide to remove it OR change it during this preview period.  This presents some risk and/or thought on how to handle this on my part.


I have a couple of questions about "User Assigned Managed Identities" in Azure.

1.  What is the use-case that would make someone pass an object_id of a user assigned identity instead of client_id ( aka appid )?
2.  Your change currently applies only to the `azure_key_vault::secret` puppet function.  Does it make sense to allow this feature to be able to be utilized for people using the hiera lookup functionality as well?  If so, can you provide an example use-case that is realistic like that shows how someone would go about using this feature with hiera?

2021-07-29 22:13 UTC, victorsecarin commented
Hey, thanks for the prompt reaction!
> It appears this feature went to public preview this month
The people who gave me  this task said:
"user-assigned has been in preview for quite some time..
I think it's out of preview now
it was in preview 2 years ago"

> What is the use-case that would make someone pass an object_id of a user assigned identity instead of client_id ( aka appid )? 
I have no idea; all I now is both work as I found by testing them. And all you need is one of them.

> Does it make sense to allow this feature to be able to be utilized for people using the hiera lookup functionality as well? 
I suppose the handling of the identity/vault access should be independent of whether it's Puppet or Hiera. I would agree  that both code areas should be upgraded. I did not do that, but I can do it if there is interest, just let me know.

2021-08-04 21:54 UTC, swheettaos commented
> Hey @victorsecarin ,
> 
> Thanks for submitting this PR.
> 
> It appears this feature went to public preview this month ( https://azure.microsoft.com/en-us/updates/azure-automation-user-assigned-identities/ | https://azure.microsoft.com/en-us/updates/?status=inpreview ) which means it's hot off the press. Being public preview this seems like it represents some risk in which microsoft might decide to remove it OR change it during this preview period. This presents some risk and/or thought on how to handle this on my part.
> 

What you are talking about is using managed identities with Azure automation (PaaS service).  Using them with other PaaS services like key vault, Azure SQL, Azure Storage has been out of preview for quite some time.  I used this for key vault access before but outside of puppet. 

I actually work with Victor.  I had him update the module and asked him to submit the PR to you.  We have tested this in our environment and it works great.  We merged it into our local repo but I asked him to submit to you so it could get added and maintained in the future.  I will most likely use this at future clients also :)

2021-08-12 14:52 UTC, TraGicCode commented
Hey @swheettaos & @victorsecarin ,

Sorry for getting back to this so late. 

I have not forgotten about this but have been busy on my end.  I will get back to this soon i promise.

2021-08-19 00:02 UTC, TraGicCode commented
Hey @swheettaos & @victorsecarin ,

Do you have real-world use-case on how you plan on pulling the client_id/object_id of the user-assigned managed identity in order to pass it to the `azure_key_vault::secret` function?  Will this be hardcoded in the .pp file, pulled in via a node fact, or pulled in via hiera?

2021-08-20 04:29 UTC, swheettaos commented
> Hey @swheettaos & @victorsecarin ,
> 
> Do you have real-world use-case on how you plan on pulling the client_id/object_id of the user-assigned managed identity in order to pass it to the `azure_key_vault::secret` function? Will this be hardcoded in the .pp file, pulled in via a node fact, or pulled in via hiera?

There are two cases. First, running the code from the node and using a User assigned identity, that is assigned to multiple machines (web servers that  need to grab creds from a vault).  Second, running the code from the server but allowing you to specify an identity to use. 

In our case we are having the nodes rather than the server reach out to the vault.  While we can do that with system assigned, it forces us to create access polices for every server vs doing it just once for a user assigned.

2021-09-10 01:55 UTC, TraGicCode requested changes
Can you fix the following small issues i mentioned along with fixing the tests?  It looks like your broke the hiera lookup.

2021-09-10 01:55 UTC, TraGicCode commented on README.md
> +We can specify a user-assigned managed identity to use instead, identified by either its 'client_id' or its 'object_id', both of which should be available from Azure upon creating that identity.
```suggestion
If you are looking to share an identity between azure resources and/or decouple the identity from the lifecycle of the azure resource then user-assigned managed identity is what you are looking for.  By Default, a system-assigned managed identity is expected to be in place and provide access to the Key Vault.  We can specify a user-assigned managed identity to use instead, identified by either its 'client_id' or its 'object_id', both of which should be available from Azure upon creating that identity.
```

2021-09-10 01:55 UTC, TraGicCode commented on lib/puppet/functions/azure_key_vault/secret.rb
> +    optional_param 'Hash',   :identity
Should we name this `user_assigned_managed_identity`?

2021-09-10 01:55 UTC, TraGicCode commented on lib/puppet/functions/azure_key_vault/secret.rb
> +      Puppet.debug("azure_key_vault::secret: explicit identity specified: #{identity}")
Can you remove the `azure_key_vault::secret:` prefix on the log statements to be consistent with the other statements in the module?

2021-09-10 01:55 UTC, TraGicCode commented on lib/puppet_x/tragiccode/azure.rb
> +      Puppet.debug("get_access_token: specified identity = #{identity}")
Please remove all the debug statements in this method

2022-02-03 03:47 UTC, closed without merging